### ISSUE TITLE
Cast button is not showing

### ISSUE THREAD

**Issue by alihussnain-git** [googlecast/CastVideos-android#103]
I have cloned this repository and run the application on my phone but cast button is not showing in action bar.

**Comment by mohamad-jawad** [comment]
cast button only appears if there are chrome-cast devices nearby, if your tv doesn't has a built-in chrome-cast it will not be considered as available device.

And if you wonder why a tv with no built-in chrome-cast appears in youtube and Netflix dialog apps, it is because these 2 applications uses DIAL protocol to communicate with their tv-version app installed in the tv.



You can reference to this article to know how youtube and Netflix uses the DIAL protocol:

https://www.howtogeek.com/215791/use-your-tv%E2%80%99s-hidden-%E2%80%9Cdial%E2%80%9D-feature-to-cast-netflix-and-youtube-without-a-chromecast/#:~:text=and%20Privacy%20Policy.-,Use%20Your%20TV's%20Hidden%20%E2%80%9CDIAL%E2%80%9D%20Feature%20to%20Cast%20Netflix,and%20YouTube%20Without%20a%20Chromecast&text=Many%20modern%20smart%20TVs%20have,computer%20%E2%80%94%20without%20getting%20a%20Chromecast.

**Comment by alihussnain-git** [comment]
@mohamad-jawad Yes button will only show if a chromecast device is nearby, sorry for late reply. Closing this.
